name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Container Apps
      run: |
        az containerapp up \
          --name indonesia-stock-predictor \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --location southeastasia \
          --environment ${{ secrets.AZURE_CONTAINER_ENV }} \
          --source . \
          --target-port 8501 \
          --ingress external \
          --env-vars \
            AZURE_OPENAI_ENDPOINT="${{ secrets.AZURE_OPENAI_ENDPOINT }}" \
            AZURE_OPENAI_API_KEY="${{ secrets.AZURE_OPENAI_API_KEY }}" \
            AZURE_OPENAI_DEPLOYMENT="${{ secrets.AZURE_OPENAI_DEPLOYMENT }}"
